server:
  port: 8092
  jetty:
    max-http-post-size: 819200

  max-http-header-size: 819200
spring:
    datasource:
#        url: jdbc:mysql://120.79.226.4:3306/nblog?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
        url: jdbc:mysql://127.0.0.1:3306/nblog?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 30000m
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

jwt:
  header: Authorization
  tokenHead: "Bearer "
  admin:
    tokenHead: "ADMIN "