server:
  port: 9090

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/nblog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
